apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-users-deployment
spec:
  selector:
    matchLabels:
      app: mysql-users
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-users
    spec:
      containers:
      - name: cassandra-patient
        image: dockerhub.accenture.com/ips/golang-mysql-users:latest
        ports:
        - containerPort: 8080